In [7]:
# One round
import random
# define a pair of poker
pair =[0,1,2,3,4,5,6,7,8,9,10,11,12,                       #Spades   2:10,J,Q,K,A
       100,101,102,103,104,105,106,107,108,109,110,111,112,#Hearts   2:10,J,Q,K,A
       200,201,202,203,204,205,206,207,208,209,210,211,212,#Clubs    2:10,J,Q,K,A
       300,301,302,303,304,305,306,307,308,309,310,311,312]#Diamonds 2:10,J,Q,K,A
# initialize player1 cards 
p1 = random.sample(pair,2)
# remove player1 cards and initialize player2 cards

pair.remove(p1[0])
pair.remove(p1[1])
p2 = random.sample(pair,2)
# remove player2 cards and initialize 3 community card
pair.remove(p2[0])
pair.remove(p2[1])
c = random.sample(pair,3)
# remove cards and initialize 1 community card
pair.remove(c[0])
pair.remove(c[1])
pair.remove(c[2])
print("First Ask")
MC_1= print_MC(p1,c)
t = random.sample(pair,1)
c = c + t
print("Second Ask")
MC_2 = print_MC(p1,c)
# remove cards and initialize the last community card
pair.remove(t[0])
tt = random.sample(pair,1)
c = c + tt
print("Third Ask")
MC_3 = print_MC(p1,c)
print("Result")
MC_final = print_result(p1,p2,c)

First Ask
player1 card: [['Spades', '3'], ['Spades', 'J']]
community card [['Diamonds', '7'], ['Clubs', '9'], ['Clubs', '8']]
win rate: 0.32543333333333335
tie rate: 0.2315
loss rate: 0.44306666666666666
Second Ask
player1 card: [['Spades', '3'], ['Spades', 'J']]
community card [['Diamonds', '7'], ['Clubs', '9'], ['Clubs', '8'], ['Diamonds', 'A']]
win rate: 0.2694666666666667
tie rate: 0.2856
loss rate: 0.44493333333333335
Third Ask
player1 card: [['Spades', '3'], ['Spades', 'J']]
community card [['Diamonds', '7'], ['Clubs', '9'], ['Clubs', '8'], ['Diamonds', 'A'], ['Hearts', '4']]
win rate: 0.07806666666666667
tie rate: 0.33926666666666666
loss rate: 0.5826666666666667
Result
player1: [['Spades', '3'], ['Spades', 'J']]
player2: [['Spades', '7'], ['Hearts', '2']]
community cards [['Diamonds', '7'], ['Clubs', '9'], ['Clubs', '8'], ['Diamonds', 'A'], ['Hearts', '4']]
Player2 win
Pair!

In [23]:
# Simulate data
def simulate(N):
    pair_0 =[0,1,2,3,4,5,6,7,8,9,10,11,12,                      
       100,101,102,103,104,105,106,107,108,109,110,111,112,
       200,201,202,203,204,205,206,207,208,209,210,211,212,
       300,301,302,303,304,305,306,307,308,309,310,311,312]
    MC_result = []
    for i in range(0,N):
        pair = pair_0.copy()
        p1 = random.sample(pair,2)
        pair.remove(p1[0])
        pair.remove(p1[1])
        p2 = random.sample(pair,2)
        pair.remove(p2[0])
        pair.remove(p2[1])
        c = random.sample(pair,3)
        pair.remove(c[0])
        pair.remove(c[1])
        pair.remove(c[2])
        MC_1= MC(p1,c)
        t = random.sample(pair,1)
        c = c + t
        MC_2 = MC(p1,c)
        pair.remove(t[0])
        c = c + random.sample(pair,1)
        MC_3 = MC(p1,c)
        MC_result = MC_result + p1 + p2 + c + MC_1 + MC_2 + MC_3 + [MCjudge(p1+c,p2+c)]
    return(MC_result)

In [27]:
#mm = simulate(1000)
simulate(1)

[2,
 301,
 110,
 206,
 311,
 3,
 312,
 201,
 5,
 0.27926666666666666,
 0.31396666666666667,
 0.40676666666666667,
 0.4023333333333333,
 0.1153,
 0.48236666666666667,
 0.48433333333333334,
 0.061566666666666665,
 0.4541,
 1]

In [24]:
import numpy as np
data = np.array( mm )
shape = ( 1000, 19 )
mmm = data.reshape( shape )
mmm
mmm.tofile('project.csv',sep=',')
np.savetxt("project_data.csv",mmm,delimiter=',')

In [36]:
# Sava data
import pandas as pd
df = pd.DataFrame(data=mmm[0:,0:],
                  index=range(0,1000),
                  columns=['P1_1','P1_2','P2_1','P2_2','C_1','C_2','C_3','C_4','C_5','1_win','1_tie',
                           '1_lose','2_win','2_tie','2_lose','3_win','3_tie','3_lose','result'])
df.to_csv('pokerdata.csv')

In [28]:
# Read data
import pandas as pd
df = pd.read_csv('pokerdata.csv')

In [29]:
df.head()

,Unnamed: 0,P1_1,P1_2,P2_1,P2_2,C_1,C_2,C_3,C_4,C_5,1_win,1_tie,1_lose,2_win,2_tie,2_lose,3_win,3_tie,3_lose,result
0,0,111,4,200,108,102,11,0,300,107,0.597600,0.069767,0.332633,0.390133,0.061900,0.547967,0.289433,0.067267,0.643300,-1
1,1,308,12,9,102,4,300,7,8,0,0.446800,0.217600,0.335600,0.668033,0.085267,0.246700,0.990600,0.000000,0.009400,1
2,2,210,308,205,200,104,303,310,311,110,0.544067,0.098967,0.356967,0.610267,0.066800,0.322933,0.842867,0.068600,0.088533,1
3,3,202,3,207,301,105,112,208,0,305,0.256367,0.307133,0.436500,0.222367,0.359233,0.418400,0.338700,0.500300,0.161000,0
4,4,107,201,111,1,5,112,307,104,302,0.488767,0.106833,0.404400,0.505867,0.087933,0.406200,0.770267,0.060133,0.169600,1

In [30]:
data = df[(df['result']==1 )|(df['result']==-1)]
data.head()

,Unnamed: 0,P1_1,P1_2,P2_1,P2_2,C_1,C_2,C_3,C_4,C_5,1_win,1_tie,1_lose,2_win,2_tie,2_lose,3_win,3_tie,3_lose,result
0,0,111,4,200,108,102,11,0,300,107,0.597600,0.069767,0.332633,0.390133,0.061900,0.547967,0.289433,0.067267,0.643300,-1
1,1,308,12,9,102,4,300,7,8,0,0.446800,0.217600,0.335600,0.668033,0.085267,0.246700,0.990600,0.000000,0.009400,1
2,2,210,308,205,200,104,303,310,311,110,0.544067,0.098967,0.356967,0.610267,0.066800,0.322933,0.842867,0.068600,0.088533,1
4,4,107,201,111,1,5,112,307,104,302,0.488767,0.106833,0.404400,0.505867,0.087933,0.406200,0.770267,0.060133,0.169600,1
5,5,5,308,101,12,1,11,108,309,6,0.508967,0.102433,0.388600,0.463000,0.083733,0.453267,0.662400,0.053967,0.283633,1

In [31]:
data.loc[data.result == -1,'result'] = 0

C:\Users\huangkejia\Anaconda3\lib\site-packages\pandas\core\indexing.py:426: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [32]:
data.head()

,Unnamed: 0,P1_1,P1_2,P2_1,P2_2,C_1,C_2,C_3,C_4,C_5,1_win,1_tie,1_lose,2_win,2_tie,2_lose,3_win,3_tie,3_lose,result
0,0,111,4,200,108,102,11,0,300,107,0.597600,0.069767,0.332633,0.390133,0.061900,0.547967,0.289433,0.067267,0.643300,0
1,1,308,12,9,102,4,300,7,8,0,0.446800,0.217600,0.335600,0.668033,0.085267,0.246700,0.990600,0.000000,0.009400,1
2,2,210,308,205,200,104,303,310,311,110,0.544067,0.098967,0.356967,0.610267,0.066800,0.322933,0.842867,0.068600,0.088533,1
4,4,107,201,111,1,5,112,307,104,302,0.488767,0.106833,0.404400,0.505867,0.087933,0.406200,0.770267,0.060133,0.169600,1
5,5,5,308,101,12,1,11,108,309,6,0.508967,0.102433,0.388600,0.463000,0.083733,0.453267,0.662400,0.053967,0.283633,1

In [33]:
del data['1_tie']
del data['2_tie']
del data['3_tie']

In [34]:
data.head()

,Unnamed: 0,P1_1,P1_2,P2_1,P2_2,C_1,C_2,C_3,C_4,C_5,1_win,1_lose,2_win,2_lose,3_win,3_lose,result
0,0,111,4,200,108,102,11,0,300,107,0.597600,0.332633,0.390133,0.547967,0.289433,0.643300,0
1,1,308,12,9,102,4,300,7,8,0,0.446800,0.335600,0.668033,0.246700,0.990600,0.009400,1
2,2,210,308,205,200,104,303,310,311,110,0.544067,0.356967,0.610267,0.322933,0.842867,0.088533,1
4,4,107,201,111,1,5,112,307,104,302,0.488767,0.404400,0.505867,0.406200,0.770267,0.169600,1
5,5,5,308,101,12,1,11,108,309,6,0.508967,0.388600,0.463000,0.453267,0.662400,0.283633,1

In [35]:
from pandas import  DataFrame
data1 = DataFrame(data,columns=['1_win','1_lose'])
data2 = DataFrame(data,columns=['2_win','2_lose'])
data3 = DataFrame(data,columns=['3_win','3_lose'])
data3.head()

      3_win    3_lose
0  0.289433  0.643300
1  0.990600  0.009400
2  0.842867  0.088533
4  0.770267  0.169600
5  0.662400  0.283633

In [36]:
result = data['result']
result.head()

0    0
1    1
2    1
4    1
5    1
Name: result, dtype: float64

In [37]:
# data
data1_t = data1[0:689]   # first 690 rows is train data
data1_v = data1[689:]    # last 100 rows is test data
data2_t = data2[0:689]
data2_v = data2[689:]
data3_t = data3[0:689]
data3_v = data3[689:]
result_t = result[0:689]
result_v = result[689:]
# Logistic Regression for 1st Monte Carlo
from sklearn.linear_model import LogisticRegression
LR_1 = LogisticRegression()
LR_1.fit(data1_t,result_t)
diff1 = LR_1.predict(data1_v)-result_v
LR_1 = 1-(sum(abs(diff1))/len(result_v))
# Logistic Regression for 2nd Monte Carlo
LR_2 = LogisticRegression()
LR_2.fit(data2_t,result_t)
diff2 = LR_2.predict(data2_v)-result_v
LR_2 = 1-(sum(abs(diff2))/len(result_v))
# Logistic Regression for 3rd Monte Carlo
LR_3 = LogisticRegression()
LR_3.fit(data3_t,result_t)
diff3 = LR_3.predict(data3_v)-result_v
LR_3 = 1-(sum(abs(diff3))/len(result_v))
print(LR_1,LR_2,LR_3)

0.55 0.63 0.82

In [38]:
# LDA for 1st Monte Carlo
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
sklearn_lda = LDA(n_components=2)
sklearn_lda.fit_transform(data1_t, result_t)
LDA_1 = 1-(sum(abs(sklearn_lda.predict(data1_v)-result_v))/len(result_v))
# LDA for 2nd Monte Carlo
sklearn_lda.fit_transform(data2_t, result_t)
LDA_2 = 1-(sum(abs(sklearn_lda.predict(data2_v)-result_v))/len(result_v))
# LDA for 3rd Monte Carlo
sklearn_lda.fit_transform(data3_t, result_t)
LDA_3 = 1-(sum(abs(sklearn_lda.predict(data3_v)-result_v))/len(result_v))
print(LDA_1,LDA_2,LDA_3)

0.54 0.65 0.82

In [39]:
# QDA for 1st Monte Carlo
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis 
QDA = QuadraticDiscriminantAnalysis()
QDA.fit(data1_t,result_t)
QDA_1 = 1-(sum(abs(QDA.predict(data1_v)-result_v))/len(result_v))
# QDA for 2nd Monte Carlo
QDA.fit(data2_t,result_t)
QDA_2 = 1-(sum(abs(QDA.predict(data2_v)-result_v))/len(result_v))
# QDA for 3rd Monte Carlo
QDA.fit(data3_t,result_t)
QDA_3 = 1-(sum(abs(QDA.predict(data3_v)-result_v))/len(result_v))
print(QDA_1,QDA_2,QDA_3)

0.56 0.58 0.8

In [40]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(data1_t, result_t)
neigh.predict(data1_v)-result_v
K1_1 = 1-(sum(abs(neigh.predict(data1_v)-result_v))/len(result_v))
neigh.fit(data2_t, result_t)
neigh.predict(data2_v)-result_v
K1_2 = 1-(sum(abs(neigh.predict(data2_v)-result_v))/len(result_v))
neigh.fit(data3_t, result_t)
neigh.predict(data3_v)-result_v
K1_3 = 1-(sum(abs(neigh.predict(data3_v)-result_v))/len(result_v))
print(K1_1,K1_2,K1_3)

neigh = KNeighborsClassifier(n_neighbors=2)
neigh.fit(data1_t, result_t)
neigh.predict(data1_v)-result_v
K2_1 = 1-(sum(abs(neigh.predict(data1_v)-result_v))/len(result_v))
neigh.fit(data2_t, result_t)
neigh.predict(data2_v)-result_v
K2_2 = 1-(sum(abs(neigh.predict(data2_v)-result_v))/len(result_v))
neigh.fit(data3_t, result_t)
neigh.predict(data3_v)-result_v
K2_3 = 1-(sum(abs(neigh.predict(data3_v)-result_v))/len(result_v))
print(K2_1,K2_2,K2_3)

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(data1_t, result_t)
neigh.predict(data1_v)-result_v
K3_1 = 1-(sum(abs(neigh.predict(data1_v)-result_v))/len(result_v))
neigh.fit(data2_t, result_t)
neigh.predict(data2_v)-result_v
K3_2 = 1-(sum(abs(neigh.predict(data2_v)-result_v))/len(result_v))
neigh.fit(data3_t, result_t)
neigh.predict(data3_v)-result_v
K3_3 = 1-(sum(abs(neigh.predict(data3_v)-result_v))/len(result_v))
print(K3_1,K3_2,K3_3)

neigh = KNeighborsClassifier(n_neighbors=4)
neigh.fit(data1_t, result_t)
neigh.predict(data1_v)-result_v
K4_1 = 1-(sum(abs(neigh.predict(data1_v)-result_v))/len(result_v))
neigh.fit(data2_t, result_t)
neigh.predict(data2_v)-result_v
K4_2 = 1-(sum(abs(neigh.predict(data2_v)-result_v))/len(result_v))
neigh.fit(data3_t, result_t)
neigh.predict(data3_v)-result_v
K4_3 = 1-(sum(abs(neigh.predict(data3_v)-result_v))/len(result_v))
print(K4_1,K4_2,K4_3)

0.55 0.58 0.7
0.54 0.55 0.67
0.54 0.57 0.74
0.55 0.51 0.72

In [41]:
method_result = pd.DataFrame(data=[
                                    [LR_1, LR_2, LR_3],
                                    [LDA_1,LDA_2,LDA_3],
                                    [QDA_1,QDA_2,QDA_3],
                                    [K1_1, K1_2,  K1_3],
                                    [K2_1, K2_2,  K2_3],
                                    [K3_1, K3_2,  K3_3],
                                    [K4_1, K4_2,  K4_3],
                                                        ],
                            index=['LG','LDA','QDA','K1','K2','K3','K4'],
                            columns=['MC_1','MC_2','MC_3'])
method_result

     MC_1  MC_2  MC_3
LG   0.55  0.63  0.82
LDA  0.54  0.65  0.82
QDA  0.56  0.58  0.80
K1   0.55  0.58  0.70
K2   0.54  0.55  0.67
K3   0.54  0.57  0.74
K4   0.55  0.51  0.72

In [46]:
# start a game
import random
# define a pair of poker
pair =[0,1,2,3,4,5,6,7,8,9,10,11,12,                       #Spades   2:10,J,Q,K,A
       100,101,102,103,104,105,106,107,108,109,110,111,112,#Hearts   2:10,J,Q,K,A
       200,201,202,203,204,205,206,207,208,209,210,211,212,#Clubs    2:10,J,Q,K,A
       300,301,302,303,304,305,306,307,308,309,310,311,312]#Diamonds 2:10,J,Q,K,A
# initialize player1 cards 
p1 = random.sample(pair,2)
# remove player1 cards and initialize player2 cards

pair.remove(p1[0])
pair.remove(p1[1])
p2 = random.sample(pair,2)
# remove player2 cards and initialize 3 community card
pair.remove(p2[0])
pair.remove(p2[1])
c = random.sample(pair,3)
# remove cards and initialize 1 community card
pair.remove(c[0])
pair.remove(c[1])
pair.remove(c[2])
print("First Ask")
MC_1= print_MC(p1,c)

First Ask
player1 card: [['Diamonds', '9'], ['Spades', '7']]
community card [['Spades', '5'], ['Spades', '10'], ['Spades', 'K']]
win rate: 0.4677
tie rate: 0.183
loss rate: 0.3493

In [55]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
sklearn_lda = LDA(n_components=2)
sklearn_lda.fit_transform(data1, result)
sklearn_lda.predict([MC_1[0],MC_1[2]])

C:\Users\huangkejia\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

array([ 1.])

In [56]:
#add one community card
t = random.sample(pair,1)
c = c + t
print("Second Ask")
MC_2 = print_MC(p1,c)

Second Ask
player1 card: [['Diamonds', '9'], ['Spades', '7']]
community card [['Spades', '5'], ['Spades', '10'], ['Spades', 'K'], ['Hearts', '4']]
win rate: 0.35273333333333334
tie rate: 0.2437
loss rate: 0.4035666666666667

In [57]:
sklearn_lda.fit_transform(data2, result)
sklearn_lda.predict([MC_2[0],MC_2[2]])

C:\Users\huangkejia\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

array([ 0.])

In [58]:
# remove cards and initialize the last community card
pair.remove(t[0])
tt = random.sample(pair,1)
c = c + tt
print("Third Ask")
MC_3 = print_MC(p1,c)

Third Ask
player1 card: [['Diamonds', '9'], ['Spades', '7']]
community card [['Spades', '5'], ['Spades', '10'], ['Spades', 'K'], ['Hearts', '4'], ['Clubs', '8']]
win rate: 0.08006666666666666
tie rate: 0.2478
loss rate: 0.6721333333333334

In [59]:
sklearn_lda.fit_transform(data3, result)
sklearn_lda.predict([MC_3[0],MC_3[2]])

C:\Users\huangkejia\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

array([ 0.])

In [60]:
print("Result")
MC_final = print_result(p1,p2,c)

Result
player1: [['Diamonds', '9'], ['Spades', '7']]
player2: [['Hearts', '3'], ['Spades', 'Q']]
community cards [['Spades', '5'], ['Spades', '10'], ['Spades', 'K'], ['Hearts', '4'], ['Clubs', '8']]
Tie
High card

In [ ]:
# One round
import random
# define a pair of poker
pair =[0,1,2,3,4,5,6,7,8,9,10,11,12,                       #Spades   2:10,J,Q,K,A
       100,101,102,103,104,105,106,107,108,109,110,111,112,#Hearts   2:10,J,Q,K,A
       200,201,202,203,204,205,206,207,208,209,210,211,212,#Clubs    2:10,J,Q,K,A
       300,301,302,303,304,305,306,307,308,309,310,311,312]#Diamonds 2:10,J,Q,K,A
# initialize player1 cards 
p1 = random.sample(pair,2)
# remove player1 cards and initialize player2 cards

pair.remove(p1[0])
pair.remove(p1[1])
p2 = random.sample(pair,2)
# remove player2 cards and initialize 3 community card
pair.remove(p2[0])
pair.remove(p2[1])
c = random.sample(pair,3)
# remove cards and initialize 1 community card
pair.remove(c[0])
pair.remove(c[1])
pair.remove(c[2])
print("First Ask")

t = random.sample(pair,1)
c = c + t
print("Second Ask")

# remove cards and initialize the last community card
pair.remove(t[0])
tt = random.sample(pair,1)
c = c + tt
print("Third Ask")

In [61]:
# define all cards conditions
def high(cards):  # find the highest card from 7 cards
    s = []
    for x in cards:
        s = [x%100 + 1] + s
    return(100+max(s))

def Pair(cards): # find the highest pairs from 7 cards
    s = []
    for x in cards:
        s = [x%100+1] +s  
    ss = []
    for x in s:  # find all pairs
        if s.count(x)==2:
            ss = ss + [x]
    if(ss):      #return the bigest one
        return(200+max(ss))
    
def TwoPair(cards):
    s = []
    for x in cards:  
        s = [x%100+1] +s
    ss = []
    for x in s:     # find all pairs
        if s.count(x)==2:
            ss = ss + [x]
    if len(ss)==4:
        return(10*ss[0]+ss[3])
    elif len(ss)==6:    # return the hightest two pairs
        ss.sort()
        t = [] 
        t = [ss[0]] + [ss[2]] + [ss[4]]
        return(300+10*t[2]+t[1])
    else:
        return(0)
def Threekind(cards):
    s = []
    for x in cards:
        s = [x%100+1] +s
    ss = []
    for x in s:         # find all threekinds
        if s.count(x)==3:
            ss = ss + [x]
    if ss :
        return(400+max(ss))  # return the bigest one
    return(0)

def Straight(cards):
    s = []
    for x in cards:   #find straight  include A,2,3,4,5
        s = [x%100+1] +s
    s.sort()
    s.reverse()
    for x in s:
        if s.count(x)>1:
            s.remove(x)
    N = len(s)
    for x in range(0,len(s)-4):
        if (s[x]==(s[(x+1)]+1) and s[(x+1)]==(s[(x+2)]+1) and s[(x+2)]==(s[(x+3)]+1) 
            and s[(x+3)]==(s[(x+4)]+1))or (s[x]==14 and s[N-1]==1 and s[N-2]==2 and s[N-3]==3 and s[N-4]==4):
            return(500+s[x])
    return(0)
def Flush(cards):
    s = []
    for x in cards:
        s = [int(x/100)] + s
    for x in s:   #find all card in same type
        if s.count(x)>4:
            ss = []
            for y in cards:
                if int(y/100) == x:
                    ss = ss + [y%100 + 1]
            ss.sort()
            ss.reverse()
            result = ss[4] + 10*ss[3] + 100*ss[2] + 1000*ss[1] + 10000*ss[0] 
            return(600+result/1000)
    return(0)
def Fullhouse(cards):
    s = []
    for x in cards:
        s = [x%100+1] +s
    n3 = 0
    n2 = 0
    ss = []
    for x in s:    # find the most bigest threekind
        if s.count(x)>2:
            ss = ss + [x] 
    if ss:
        n3 = max(ss)
    for x in s:  # find the bigest pairs
        if s.count(x)>1 and x!=n3:
            n2 = x
    if n3 and n2:
        return(700+10*n3 + n2)
    return(0)
def Four(cards):   #
    s = []
    for x in cards:
        s = [x%100+1] +s
    for x in s:
        if s.count(x)>3:
            return(800+x)
    return(0)
def StraightFlush(cards):
    s = []
    for x in cards:
        s = [int(x/100)] + s
    ss = []
    for x in s:
        if s.count(x)>4:
            for y in cards:
                if int(y/100) == x:
                    ss = ss + [y%100 + 1]
            ss.sort()
    if len(ss)>4 or len(ss)==4:
        for x in range(0,len(ss)-4):
            if (ss[x]+1==ss[(x+1)] and ss[(x+1)]+1==ss[(x+2)] and ss[(x+2)]+1==ss[(x+3)] and ss[(x+3)]+1==ss[(x+4)]):
                return(900+ss[x+4])
    return(0)
def RoyalFlush(cards):
    if StraightFlush(cards)==14:
        return(1000)
    return(0)   
# define function to judge which player win
def get_rank(cards):  # find the best cards type
        final = 'High card'  # only return the last result
        result = high(cards)
        if Pair(cards):
            final = 'Pair!'
            result = Pair(cards)
        if TwoPair(cards):
            final = 'Two pairs!'
            result = TwoPair(cards)
        if Threekind(cards):
            final = 'Three of a kind!'
            result = Threekind(cards)
        if Straight(cards):
            final = 'Straight'
            result = Straight(cards)
        if Flush(cards):
            final = 'Flush'
            result = Flush(cards)
        if Fullhouse(cards):
            final = 'Full house!'
            result = Fullhouse(cards)
        if Four(cards):
            final = 'Four of a kind!'
            result = Four(cards)
        if StraightFlush(cards):
            final = "Straight Flush!"
            result = StraightFlush(cards)
        if RoyalFlush(cards):
            final = "Royal Flush!"
            result = RoyalFlush(cards)
        result = [result,final]
        return result
def switch(cards):  #  to print out the cards
    s=[]
    for m in cards:
        x = int(m/100)
        y = int(m)%100 +2 
        if(x == 0):
            cc = 'Spades'
        if(x == 1):
            cc = 'Hearts'
        if(x == 2):
            cc = 'Clubs'
        if(x == 3):
            cc = 'Diamonds'
        if(y == 11):
            y = 'J'
        if(y == 12):
            y = 'Q'
        if(y == 13):
            y = 'K'
        if(y == 14):
            y = 'A'
        s= s + [[cc] + [str(y)]]
    return(s)
def judge(card1, card2):  # to judge the result of the game,  player1 win or tie or lose 
    if get_rank(card1)[0] > get_rank(card2)[0]:
        print("Player1 win")
        print(get_rank(card1)[1])
        
    if get_rank(card1)[0] == get_rank(card2)[0]:
        print("Tie")
        print(get_rank(card1)[1])
       
    if get_rank(card1)[0] < get_rank(card2)[0]:
        print("Player2 win")
        print(get_rank(card2)[1])
        
def MCjudge(card1,card2):  #  1 means play1 win , 0 means tie, -1 means play1 lose
    if get_rank(card1)[0] > get_rank(card2)[0]:
        return(1)
    if get_rank(card1)[0] == get_rank(card2)[0]:
        return(0)
    if get_rank(card1)[0] < get_rank(card2)[0]:
        return(-1)
def print_MC(p1,c):
    result = MC(p1,c)
    print("player1 card:", switch(p1))
    print("community card", switch(c))
    print("win rate:",result[0])
    print("tie rate:",result[1])
    print("loss rate:",result[2])
    return(result)
#judge which player is better
def print_result(p1,p2,c):
    play1 = p1 + c
    play2 = p2 + c
    print("player1:",switch(p1))
    print("player2:",switch(p2))
    print("community cards",switch(c))
    judge(play1,play2)
    return(MCjudge(play1,play2))

In [3]:
# Monte Carlo simulation judge who will win
def MC(p1,c):  # use player1 cards, and community cards, it can 3, 4 or 5
    n = 5 - len(c)
    pair = [0,1,2,3,4,5,6,7,8,9,10,11,12,                   #Spades   2:10,J,Q,K,A
       100,101,102,103,104,105,106,107,108,109,110,111,112, #Hearts   2:10,J,Q,K,A
       200,201,202,203,204,205,206,207,208,209,210,211,212, #Clubs    2:10,J,Q,K,A
       300,301,302,303,304,305,306,307,308,309,310,311,312] #Diamonds 2:10,J,Q,K,A
    pair.remove(p1[0])
    pair.remove(p1[1])
    for x in range(0,(len(c)-1)):
        pair.remove(c[x])
    sumwin = 0
    sumtie = 0
    M = 30000
    if(n>0):
        for m in range(1,M):  # simulate player2 cards and other community cards
            pair_MC = pair.copy()
            p2 = random.sample(pair_MC,2)
            pair_MC.remove(p2[0])
            pair_MC.remove(p2[1])
            t = random.sample(pair_MC,n)
            play1 = c + p1 + t
            play2 = c + p2 + t
            ans = MCjudge(play1,play2)  # judge the result of the game
            if(ans==1):
                sumwin = sumwin + 1
            if(ans==0):
                sumtie = sumtie + 1
    if(n==0): # if there are 5 community cards
        for m in range(1,M):
            pair_MC = pair.copy()
            p2 = random.sample(pair_MC,2)
            play1 = c + p1 
            play2 = c + p2
            ans = MCjudge(play1,play2)
            if(ans==1):
                sumwin = sumwin + 1
            if(ans==0):
                sumtie = sumtie + 1
    ratewin = sumwin / M
    ratetie = sumtie / M
    result = [ratewin, ratetie,((M-sumwin-sumtie)/M)]   # return win rate, tie rate and lose rate
    return(result)